### ISSUE TITLE
Type Error on 5.2.0 version.

### ISSUE THREAD

**Issue by eugenepro2** [lookinlab/adonis-lucid-filter#44]
There is an issue after upgrading to 5.2.0
```
 "@adonisjs/lucid": "^21.2.0",
 "adonis-lucid-filter": "5.2.0",
 ```

```
Property 'filter' does not exist on type 'ModelQueryBuilderContract<typeof Category, Category>'.
```

Version 5.1.0 doesn't have any errors.

**Comment by micheledicati** [comment]
You may have already solved the problem, but I had the same problem and solved it by writing a file in app/types/adonis_lucid_filter.ts with just this line of code:
import 'adonis-lucid-filter/types/querybuilder'
